### ISSUE TITLE
一直提示这个错误，能否看下channel.yaml是怎么对应AndroidManifest.xml channel的

### ISSUE THREAD

**Issue by Roc-egg** [9yao/bindchannels#1]
![image](https://github.com/9yao/bindchannels/assets/15016163/fa1d62a4-227e-41e5-8a53-89500d904fa3)

**Comment by 9yao** [comment]
能提供一下，你目前的key.yaml channel.yaml的相关配置和使用的系统？你也可以点击更多观看抖音视频进行解决。希望能帮到你

**Comment by 9yao** [comment]
能提供一下，你目前的key.yaml channel.yaml的相关配置和使用的系统？你也可以点击更多观看抖音上的视频进行解决。希望能帮到你

**Comment by 9yao** [comment]
channel.yaml 是配置你需要签名的多渠道包
keys.yaml 是配置你的签名信息

**Comment by Roc-egg** [comment]
windows11  jdk17

**Comment by Roc-egg** [comment]
windows11 jdk17  

packageName:
  keyPath: '/jks/test.keystore'
  alias: '111'
  keyPwd: '123'
  storePwd: '123'
  
  outChannelName: '# in AndroidManifest.xml channel name if not is marketChannel used'
marketChannel:
- qq
- huawei


AndroidManifest.xml
        <meta-data
            android:name="marketChannel"
            android:value="50000" />

**Comment by 9yao** [comment]
您的keys.yaml文件内容不对；最好用文本文件打开编辑。
1、您需要将packageName改成您的待处理包的包名（AndroidManifest.xml中的package）
2、keyPath 路径最好写成绝对路径 如：C:/Users/admin/.android/debug.keystore
3、请不要随便修改yaml文件的缩进；请熟悉yaml文件格式
4、windows设备，可能还需要验证apksigner命令是否能正常访问；如果不能您需要在keys.yaml文件里加如下信息：
4.1、
`apkSignerCmd : java -jar apksigner.jar的具体路径`
可以参考如下截图：
<img width="406" alt="WechatIMG2" src="https://github.com/9yao/bindchannels/assets/153906726/053e080e-013f-4247-b7de-73e030cf74bb">

channel.yaml 中的outChannelName: 字段要配置成您的待处理包里的渠道名，如果包里的渠道名也定义成marketChannel，可以忽略这个字段
